package osproject;


import java.beans.PropertyVetoException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ravi
 */
public class Scheduling extends javax.swing.JInternalFrame {
    int[][] b=new int[100][4];
        Random r=new Random();
        Random r3=new Random();
        int n=4;
        int count;
    /**
     * Creates new form S_Algo
     * @param cnt
     */
    public Scheduling(int cnt) {
        initComponents();
        count=cnt;
        for(int i=0;i<n;i++)
		for(int j=0;j<2;j++)
			b[i][j]=(r.nextInt(10)+r3.nextInt(10));
	for(int j=0;j<n;j++)
		b[j][2]=0;
        for(int j=0;j<n;j++)
		b[j][3]=0;
        for(int j=0;j<n;j++)
        {
            ta.append(b[j][0]+" "+b[1][j]+" "+b[j][2]+" "+b[j][3]);
            ta.append("\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        t7 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();

        jLabel1.setText("Algorithm");

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButton1.setText("FCFS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SJF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SRTF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("PS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("PS(p)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Algorithm");

        jLabel3.setText("AWT");

        jLabel4.setText("Time Quantum");

        jButton6.setText("RR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[][] a=new int[100][3];
        int sum,k,t,count,time;
        double avg;
        for(int i=0;i<n;i++)
        for(int j=0;j<3;j++)
        a[i][j]=b[i][j];
        for(int i=0;i<n;i++)
        for(int j=i;j<n;j++)
        if(a[i][0]>a[j][0])
        {
            k=a[i][0];
            t=a[i][1];
            a[i][0]=a[j][0];
            a[i][1]=a[j][1];
            a[j][0]=k;
            a[j][1]=t;
        }
        /*for(int i=0;i<n;i++)
        {	for(int j=0;j<2;j++)
            System.out.print(a[i][j]+" ");
            System.out.print("\n");
        }*/
        count=0;
        time=0;
        while(count<n)
        {
            if(a[count][1]==0)
            count++;

            if(a[count][1]>0)
            a[count][1]--;

            for(int i=count+1;i<n;i++)
            if(a[i][0]<=time)
            a[i][2]++;

            time++;
        }
        ta.append("\n");
        ta.append("FCFS: "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        sum=0;
        for(int i=0;i<n;i++)
        sum+=a[i][2];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t1.setText(""+avg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int[][] a=new int[100][3];
        int count,time,k,t,sum,l;
        double avg;boolean bool=false;
        for(int i=0;i<n;i++)
        for(int j=0;j<3;j++)
        a[i][j]=b[i][j];
        for(int i=0;i<n;i++)
        {
            for(int j=i;j<n;j++)
            {
                if(a[i][0]>a[j][0])
                {
                    k=a[i][0];
                    t=a[i][1];
                    a[i][0]=a[j][0];
                    a[i][1]=a[j][1];
                    a[j][0]=k;
                    a[j][1]=t;
                }
                if(a[i][0]==a[j][0])
                {
                    if(a[i][1]>a[j][1])
                    {
                        k=a[i][1];
                        a[i][1]=a[j][1];
                        a[j][1]=k;
                    }

                }
            }
        }
        for(int i=0;i<n;i++)
        a[i][2]=0;

        time=0;
        count=0;
        while(count<n)
        {

            if(a[count][1]==0)
            {
                for(int i=count+1;i<n;i++)
                {
                    for(int j=i;j<n;j++)
                    {
                        if(a[i][0]<=time && a[j][0]<=time)
                        {
                            if(a[i][1]>a[j][1])
                            {
                                k=a[i][0];
                                t=a[i][1];
                                l=a[i][2];
                                a[i][0]=a[j][0];
                                a[i][1]=a[j][1];
                                a[i][2]=a[j][2];
                                a[j][0]=k;
                                a[j][1]=t;
                                a[j][2]=l;
                            }
                            if(a[i][1]==a[j][1])
                            {
                                if(a[i][0]>a[j][0])
                                {
                                    k=a[i][0];
                                    t=a[i][1];
                                    l=a[i][2];
                                    a[i][0]=a[j][0];
                                    a[i][1]=a[j][1];
                                    a[i][2]=a[j][2];
                                    a[j][0]=k;
                                    a[j][1]=t;
                                    a[j][2]=l;
                                }

                            }
                        }
                        else
                        {
                            bool=true;
                            break;
                        }
                    }
                    if(bool)
                    {
                        bool=false;
                        break;
                    }

                }
                if(a[count+1][0]<=time)
                count++;
            }
            if(a[count][1]>0)
            a[count][1]--;

            for(int i=count+1;i<n;i++)
            if(a[i][0]<=time)
            a[i][2]++;

            time++;
        }
        ta.append("\n");
        ta.append("SJF: "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        sum=0;
        /*for(int i=0;i<n;i++)
        System.out.print(a[i][2]+" ");
        System.out.print("\n");*/
        for(int i=0;i<n;i++)
        sum+=a[i][2];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t2.setText(""+avg);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int[][] a=new int[100][3];
        int count,time,k,t,sum,l;
        double avg;boolean bool=false;
        for(int i=0;i<n;i++)
        for(int j=0;j<3;j++)
        a[i][j]=b[i][j];
        for(int i=0;i<n;i++)
        {
            for(int j=i;j<n;j++)
            {
                if(a[i][0]>a[j][0])
                {
                    k=a[i][0];
                    t=a[i][1];
                    a[i][0]=a[j][0];
                    a[i][1]=a[j][1];
                    a[j][0]=k;
                    a[j][1]=t;
                }
                if(a[i][0]==a[j][0])
                {
                    if(a[i][1]>a[j][1])
                    {
                        k=a[i][1];
                        a[i][1]=a[j][1];
                        a[j][1]=k;
                    }

                }
            }
        }
        time=0;
        count=0;
        while(count<n)
        {

            for(int i=0;i<n;i++)
            {
                for(int j=i+1;j<n;j++)
                {
                    if(a[i][0]<=time && a[j][0]<=time)
                    {
                        if(a[i][1]>a[j][1])
                        {
                            k=a[i][0];
                            t=a[i][1];
                            l=a[i][2];
                            a[i][0]=a[j][0];
                            a[i][1]=a[j][1];
                            a[i][2]=a[j][2];
                            a[j][0]=k;
                            a[j][1]=t;
                            a[j][2]=l;
                        }
                        if(a[i][1]==a[j][1])
                        {
                            if(a[i][0]>a[j][0])
                            {
                                k=a[i][0];
                                t=a[i][1];
                                l=a[i][2];
                                a[i][0]=a[j][0];
                                a[i][1]=a[j][1];
                                a[i][2]=a[j][2];
                                a[j][0]=k;
                                a[j][1]=t;
                                a[j][2]=l;
                            }

                        }
                    }
                    else
                    {
                        bool=true;
                        break;
                    }
                }
                if(bool)
                {
                    bool=false;
                    break;
                }
            }
            if(a[count][1]==0)
            count++;
            if(a[count][1]>0)
            a[count][1]--;
            for(int i=0;i<n;i++)
            if(a[i][0]<=time && a[count][0]!=a[i][0] && a[i][1]!=0)
            a[i][2]++;
            time++;
        }
        ta.append("\n");

        sum=0;
        ta.append("SRTF: "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        /*for(int i=0;i<n;i++)
        System.out.print(a[i][2]+" ");
        System.out.print("\n");*/
        for(int i=0;i<n;i++)
        sum+=a[i][2];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t3.setText(""+avg);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int[][] a=new int[100][4];
        int count=0,time,k,t,sum,l,m,k1;
        double avg;boolean bool=false;
        for(int i=0;i<n;i++)
        for(int j=0;j<4;j++)
        a[i][j]=b[i][j];
        Random r2=new Random();
        Random r1=new Random();
        while(count<n)
        {
            k=r2.nextInt(n);
            k1=r1.nextInt(n);
            k1=(k+k1)%(n+1);
            //System.out.println(k);
            for(int i=0;i<n;i++)
            {
                if(k1==a[i][2])
                {
                    bool=true;
                    break;
                }

            }
            if(!bool)
            {
                a[count][2]=k1;
                count++;
            }
            bool=false;
        }
        bool=false;
        for(int i=0;i<n;i++)
        {
            for(int j=i;j<n;j++)
            {
                if(a[i][0]>a[j][0])
                {
                    k=a[i][0];
                    t=a[i][1];
                    l=a[i][2];
                    a[i][0]=a[j][0];
                    a[i][1]=a[j][1];
                    a[i][2]=a[j][2];
                    a[j][0]=k;
                    a[j][1]=t;
                    a[j][2]=l;
                }
                if(a[i][0]==a[j][0])
                {
                    if(a[i][2]>a[j][2])
                    {
                        t=a[i][1];
                        l=a[i][2];
                        a[i][1]=a[j][1];
                        a[i][2]=a[j][2];
                        a[j][1]=t;
                        a[j][2]=l;
                    }

                }
            }
        }
        for(int i=0;i<n;i++)
        a[i][3]=0;
        time=0;
        count=0;
        while(count<n)
        {

            if(a[count][1]==0)
            {
                for(int i=count+1;i<n;i++)
                {
                    for(int j=i;j<n;j++)
                    {
                        if(a[i][0]<=time && a[j][0]<=time)
                        {
                            if(a[i][2]>a[j][2])
                            {
                                k=a[i][0];
                                t=a[i][1];
                                l=a[i][2];
                                m=a[i][3];
                                a[i][0]=a[j][0];
                                a[i][1]=a[j][1];
                                a[i][2]=a[j][2];
                                a[i][3]=a[j][3];
                                a[j][0]=k;
                                a[j][1]=t;
                                a[j][2]=l;
                                a[j][3]=m;
                            }
                        }
                        else
                        {
                            bool=true;
                            break;
                        }
                    }
                    if(bool)
                    {
                        bool=false;
                        break;
                    }

                }
                if(a[count+1][0]<=time)
                count++;
            }
            if(a[count][1]>0)
            a[count][1]--;

            for(int i=count+1;i<n;i++)
            if(a[i][0]<=time)
            a[i][3]++;
            /*for(int i=0;i<n;i++)
            {
                for(int j=0;j<4;j++)
                System.out.print(a[i][j]+" ");
                System.out.println();
            }
            System.out.println();*/
            time++;
        }
        ta.append("\n");
        ta.append("PS: "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        sum=0;
        /*for(int i=0;i<n;i++)
        System.out.print(a[i][3]+" ");
        System.out.print("\n");*/
        for(int i=0;i<n;i++)
        sum+=a[i][3];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t4.setText(""+avg);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int[][] a=new int[100][4];
        int count=0,time=0,k,t=0,sum,l,k1,m;
        double avg;boolean bool=false;
        for(int i=0;i<n;i++)
        for(int j=0;j<4;j++)
        a[i][j]=b[i][j];
        Random r2=new Random();
        Random r1=new Random();
        while(count<n)
        {
            k=r2.nextInt(n);
            k1=r1.nextInt(n);
            k1=(k+k1)%(n+1);
            //System.out.println(k);
            for(int i=0;i<n;i++)
            {
                if(k1==a[i][2])
                {
                    bool=true;
                    break;
                }

            }
            if(!bool)
            {
                a[count][2]=k1;
                count++;
            }
            bool=false;
        }
        bool=false;
        /*for(int i=0;i<n;i++)
        {	for(int j=0;j<3;j++)
            System.out.print(a[i][j]+" ");
            System.out.println();
        }*/
        for(int i=0;i<n;i++)
        {
            for(int j=i;j<n;j++)
            {
                if(a[i][0]>a[j][0])
                {
                    k=a[i][0];
                    t=a[i][1];
                    l=a[i][2];
                    a[i][0]=a[j][0];
                    a[i][1]=a[j][1];
                    a[i][2]=a[j][2];
                    a[j][0]=k;
                    a[j][1]=t;
                    a[j][2]=l;
                }
                if(a[i][0]==a[j][0])
                {
                    if(a[i][2]>a[j][2])
                    {
                        t=a[i][1];
                        l=a[i][2];
                        a[i][1]=a[j][1];
                        a[i][2]=a[j][2];
                        a[j][1]=t;
                        a[j][2]=l;
                    }

                }
            }
        }
        /* for(int i=0;i<n;i++)
        {	for(int j=0;j<3;j++)
            System.out.print(a[i][j]+" ");
            System.out.println();
        }*/
        time=0;
        count=0;
        while(count<n)
        {

            for(int i=0;i<n;i++)
            {
                for(int j=i+1;j<n;j++)
                {
                    if(a[i][0]<=time && a[j][0]<=time)
                    {
                        if(a[i][2]>a[j][2])
                        {
                            k=a[i][0];
                            t=a[i][1];
                            l=a[i][2];
                            m=a[i][3];
                            a[i][0]=a[j][0];
                            a[i][1]=a[j][1];
                            a[i][2]=a[j][2];
                            a[i][3]=a[j][3];
                            a[j][0]=k;
                            a[j][1]=t;
                            a[j][2]=l;
                            a[j][3]=m;
                        }
                    }
                    else
                    {
                        bool=true;
                        break;
                    }
                }
                if(bool)
                {
                    bool=false;
                    break;
                }
            }
            if(a[count][1]==0)
            count++;
            if(a[count][1]>0)
            a[count][1]--;
            for(int i=0;i<n;i++)
            if(a[i][0]<=time && a[count][2]!=a[i][2] && a[i][1]!=0)
            a[i][3]++;
            /*for(int i=0;i<n;i++)
            {
                for(int j=0;j<4;j++)
                System.out.print(a[i][j]+" ");
                System.out.println();
            }
            System.out.println();*/
            time++;
        }
        ta.append("\n");
        ta.append("PS(p): "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        sum=0;
        /*for(int i=0;i<n;i++)
        System.out.print(a[i][3]+" ");
        System.out.print("\n");*/
        for(int i=0;i<n;i++)
        sum+=a[i][3];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t5.setText(""+avg);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[][] a=new int[100][3];
        int sum,k,t,count,time,var,tc;
        tc=Integer.parseInt(t7.getText());
        double avg;
        for(int i=0;i<n;i++)
        for(int j=0;j<3;j++)
        a[i][j]=b[i][j];
        for(int i=0;i<n;i++)
        for(int j=i;j<n;j++)
        if(a[i][0]>a[j][0])
        {
            k=a[i][0];
            t=a[i][1];
            a[i][0]=a[j][0];
            a[i][1]=a[j][1];
            a[j][0]=k;
            a[j][1]=t;
        }
        count=0;
        time=0;
        int l=0;
        var=0;
        while(count<n)
        {
            l=l%n;
            if(a[count][1]==0)
            count++;
            if((a[l][1]-tc)<0)
            var=a[l][1];
            else
            var=tc;
            if(a[l][1]>0)
            a[l][1]-=var;
            time+=var;
            for(int i=0;i<n;i++)
            {

                if(a[i][0]<=time && a[i][1]>0 && i!=l)
                {
                    a[i][2]+=var;
                }
            }
            l+=1;
        }
        ta.append("\n");
        ta.append("RR: "+a[0][2]+" "+a[1][2]+" "+a[2][2]+" "+a[3][2]);
        ta.append("\n");
        sum=0;
        /*for(int i=0;i<n;i++)
        System.out.print(a[i][2]+" ");
        System.out.print("\n");*/
        for(int i=0;i<n;i++)
            sum+=a[i][2];
        avg=n*1.0;
        avg=sum/avg;
        avg=Math.round(avg*100.0);
        avg=avg/100.0;
        t6.setText(""+avg);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Home.processList.removeItem("Scheduling");
        Home.sc[count]=null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        for(int j=0;j<10;j++){
                System.out.println(j+" value of i");
                if(Home.cal[j]!=null){
                    
                    try {
                        Home.cal[j].setIcon(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                if(Home.np[j]!=null){
                    try {
                            Home.np[j].setIcon(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if(Home.sc[j]!=null&&j!=count){
                    try {
                            Home.sc[j].setIcon(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if(Home.ter[j]!=null){
                    try {
                            Home.ter[j].setIcon(true);
                    } catch (PropertyVetoException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_formInternalFrameDeiconified
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
